on:
  push:
permissions:
  actions: write
  checks: write
  pull-requests: write
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - name: Set up Java 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'
    #     distribution: 'adopt'
    # # Because this example is building a Gradle project, it needs to happen after setting up Java
    # - name: Grant execute permission for gradlew to build my project
    #   run: chmod +x gradlew
    # - name: Build my project with Gradle
    #   run: ./gradlew build
    - name: Create Black Duck Policy
      uses: blackducksoftware/create-policy-action@v0.0.1
      with:
        blackduck-url: ${{ secrets.BLACKDUCK_URL }}
        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
        policy-name: 'My Black Duck Policy For GitHub Actions'
        no-fail-if-policy-exists: true
    - name: Run Synopsys Detect
      uses: synopsys-sig/detect-action@v0.3.4
      env:
        DETECT_TOOLS: DETECTOR,SIGNATURE_SCAN
        DETECT_PROJECT_USER_GROUPS: OSSCA
        DETECT_PROJECT_GROUP_NAME: OSSCA
        DETECT_PROJECT_NAME: "test"
        DETECT_PROJECT_VERSION_NAME: "vtest2"
        DETECT_PROJECT_TAGS: vcb,mcr,raz,tcc
        DETECT_CODE_LOCATION_NAME: test/vtest
        DETECT_BLACKDUCK_SIGNATURE_SCANNER_COPYRIGHT_SEARCH: true
        DETECT_BLACKDUCK_SIGNATURE_SCANNER_LICENSE_SEARCH: true
        DETECT_BLACKDUCK_SIGNATURE_SCANNER_UPLOAD_SOURCE_MODE: true
        DETECT_EXCLUDED_DIRECTORIES: dist
        DETECT_SOURCE_PATH: src
      with:
          scan-mode: INTELLIGENT          
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 8.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
